### PR TITLE
support clusterproperties

### PR DESCRIPTION
**Pull request by vhdirk**
This brings support for computing properties for automatic clustering. I'm not sure if the implementation for iOS is sane; I have no experience in that area.

### CODE REVIEW

**Comment by keerl** [comment]
That most recent commit is not needed as that will be generated by lerna when a new version is published. Any chance you could remove those changes (all the versioning stuff)?

Do you happen to have any example code that we could turn into a demo for this clustering? If not, we can just publish this out.

**Comment by vhdirk** [comment]
That last commit was erroneous, indeed. I am working on a small demo but so far haven't gotten it to work.

**Comment by vhdirk** [comment]
I don't have a standalone example, but this bit here seems to work as expected: https://github.com/vhdirk/knots/blob/main/src/app/home/home.component.ts#L134

**Comment by keerl** [comment]
I'm unable to open that link. Is that a private repo?

**Comment by vhdirk** [comment]
Ah, yes, indeed. It was :)

**Comment by keerl** [comment]
I don't really have time to test this out right now but don't want to leave this PR hanging so I merged it in and published a new version `6.2.13`.

**Pull request merged**
