### PR TITLE
Fix for Padding

### PR DESCRIPTION
**Pull request by oliverphaser**
I added the option to define padding for each side (top, bottom, left, right) in the setViewPort function.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@oliverphaser thanks a lot. I think it would be best to test for "`typeof ... === 'object'`. The reason is that right now if you were to pass `{top:10}` it would crash(because bottom,left, right would be passed an object when it expects a number) when it should mean only padding top of 10.

**Comment by oliverphaser** [comment]
> @oliverphaser thanks a lot. I think it would be best to test for "`typeof ... === 'object'`. The reason is that right now if you were to pass `{top:10}` it would crash(because bottom,left, right would be passed an object when it expects a number) when it should mean only padding top of 10.

Right, sorry I was in hurry. I did it now, please check. It's a perfect plugin, I should say thanks. :)

**Comment by oliverphaser** [comment]
> @oliverphaser thanks a lot. I think it would be best to test for "`typeof ... === 'object'`. The reason is that right now if you were to pass `{top:10}` it would crash(because bottom,left, right would be passed an object when it expects a number) when it should mean only padding top of 10.

Right, sorry I was in a hurry. I did it now, please check. It’s a perfect plugin, I should say thanks. :)

**Comment by farfromrefug** [comment]
@oliverphaser dont apologize! it looks good now
Thanks

**Comment by farfromrefug** [comment]
@oliverphaser it is released!
thanks again

**Pull request merged**
