### PR TITLE
fix(tracking user): tracking the user was not implemented on iOS

### PR DESCRIPTION
**Pull request by benedictstrube**
Added implementation to track the user with different heading modes (`UserLocationCameraMode`).

### CODE REVIEW

**Comment by keerl** [comment]
Merged all your PRs and just published in 6.2.15. Let me know if you would like to become a NativeScript Community member so you could merge and publish versions out yourself. It seems like you are using mapbox more than I am.

**Comment by benedictstrube** [comment]
Hey @keerl, thank you very much for that swift merge! I would be happy to become a Nativescript Community member. In fact, the app I am currently developing uses a lot of map functionality (creating and managing custom routes, navigation etc.). Before this community version existed, we had forked the previous Nativescript Mapbox repo and added functionality and improved the plugin to fit our needs. As we decided to switch to the Community version, I am currently transferring the functionality I previously added.

**Comment by keerl** [comment]
Cool, I just send you an invite to join. I'll have to have someone else add your email for NPM publishing. Do you have an existing NPM account?

**Comment by benedictstrube** [comment]
Yes, I do: it's [benedictstrube](https://www.npmjs.com/~benedictstrube)!

**Pull request merged**
